---
title: "Bin Chen Disease DGE Drug Connectivity Score"
output: rmarkdown::html_vignette
author: "Carmelo Catalano"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
vignette: >
 %\VignetteIndexEntry{Bin Chen Disease DGE Drug Connectivity Score}
 %\VignetteEngine{knitr::rmarkdown}
 %\VignetteEncoding{UTF-8}
---
# Description
Given a disease DGE and a drug DGE, computes the connectivity score between them.
```{r setup, include=FALSE}
library(DrugRepurposing)
```
```{r}
library(DrugRepurposing)
disease_dge <- data.frame(
  gene_id = c(1, 2, 3, 9, 11, 15),
  t.value = c(-9.261609, -10.36986, 8.17305166, 5.60715925, -8.444215, 7.12957687)
)

drug_dge <- data.frame(
  gene_id = c(1, 2, 3, 10, 11, 13),
  t.value = c(-2.26559, 1.369012, 3.173466, -4.60136, -2.191482, 4.2035724)
)

binChenDiseaseDGEDrugConnectivityScore <- BinChenDiseaseDGEDrugConnectivityScore$new()
binChenDiseaseDGEDrugConnectivityScore$compute(
  disease_dge = disease_dge,
  drug_dge = drug_dge,
  drug_dge_t_value_column_name = "t.value",
  random_distribution_size = 10, # 10 is a poor value used only to speed up
                                 # computation; an appropriate value is 10^5
  compute_p_value = TRUE,
  signature_mapper_parameter = 4
)
```
